name: tech_docs_generator
description: "Technical Documents Generator is an powered tool that generates comprehensive project briefs, SRS, etc based on user inputs, streamlining project planning and communication."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pdf: ^3.10.8
  printing: ^5.12.0
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  get: ^4.7.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
